### RECUPERATION DE LA LISTE DES APPARTEMENTS
GET http://localhost:8000/api/appartements

###INSERER UN NOUVEAU APPARTEMENT
POST http://localhost:8000/api/appartements
Content-Type: application/json

{
    "numero_etage":3,
    "numero_appartement":18,
    "superficie":35,
    "nbr_chambre":3,
    "prix_previsionnel":200000,
    "immeuble_id":6,
    "type":"9"
}

### RECUPERATION D'UN SEUL APPARTEMENT
GET http://localhost:8000/api/appartements/1

###MISE A JOUR UN NOUVEAU APPARTEMENT
PUT http://localhost:8000/api/appartements/1
Content-Type: application/json

{
    "numero_etage":4,
    "numero_appartement":29,
    "superficie":50,
    "nbr_chambre":4,
    "prix_previsionnel":200000,
    "immeuble_id":5,
    "type":"0"
}

### SUPPRESSION D'UN SEUL APPARTEMENT
DELETE http://localhost:8000/api/appartements/1